// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	proxy "github.com/nusiss-capstone-project/payment-mservice/server/proxy"
	mock "github.com/stretchr/testify/mock"
)

// StripeProxy is an autogenerated mock type for the StripeProxy type
type StripeProxy struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: ctx, req
func (_m *StripeProxy) CreateCustomer(ctx context.Context, req proxy.CreateCustomerRequest) (*proxy.Customer, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomer")
	}

	var r0 *proxy.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.CreateCustomerRequest) (*proxy.Customer, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, proxy.CreateCustomerRequest) *proxy.Customer); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, proxy.CreateCustomerRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePayment provides a mock function with given fields: ctx, req
func (_m *StripeProxy) CreatePayment(ctx context.Context, req proxy.CreatePaymentRequest) (*proxy.Payment, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *proxy.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.CreatePaymentRequest) (*proxy.Payment, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, proxy.CreatePaymentRequest) *proxy.Payment); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, proxy.CreatePaymentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePaymentMethodSetup provides a mock function with given fields: ctx, req
func (_m *StripeProxy) CreatePaymentMethodSetup(ctx context.Context, req proxy.SetupPaymentMethodRequest) (*proxy.SetupSession, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentMethodSetup")
	}

	var r0 *proxy.SetupSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.SetupPaymentMethodRequest) (*proxy.SetupSession, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, proxy.SetupPaymentMethodRequest) *proxy.SetupSession); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.SetupSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, proxy.SetupPaymentMethodRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPayment provides a mock function with given fields: ctx, paymentID
func (_m *StripeProxy) GetPayment(ctx context.Context, paymentID string) (*proxy.Payment, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 *proxy.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*proxy.Payment, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *proxy.Payment); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentMethodBySetupIntent provides a mock function with given fields: ctx, setupIntentID
func (_m *StripeProxy) GetPaymentMethodBySetupIntent(ctx context.Context, setupIntentID string) (*proxy.PaymentMethodInfo, error) {
	ret := _m.Called(ctx, setupIntentID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentMethodBySetupIntent")
	}

	var r0 *proxy.PaymentMethodInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*proxy.PaymentMethodInfo, error)); ok {
		return rf(ctx, setupIntentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *proxy.PaymentMethodInfo); ok {
		r0 = rf(ctx, setupIntentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.PaymentMethodInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, setupIntentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseWebhookEvent provides a mock function with given fields: ctx, payload, signature
func (_m *StripeProxy) ParseWebhookEvent(ctx context.Context, payload []byte, signature string) (*proxy.WebhookEvent, error) {
	ret := _m.Called(ctx, payload, signature)

	if len(ret) == 0 {
		panic("no return value specified for ParseWebhookEvent")
	}

	var r0 *proxy.WebhookEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) (*proxy.WebhookEvent, error)); ok {
		return rf(ctx, payload, signature)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) *proxy.WebhookEvent); ok {
		r0 = rf(ctx, payload, signature)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.WebhookEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string) error); ok {
		r1 = rf(ctx, payload, signature)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStripeProxy creates a new instance of StripeProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStripeProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *StripeProxy {
	mock := &StripeProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
