// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	identitypb "github.com/nusiss-capstone-project/identity-mservice/common/identitypb"
	mock "github.com/stretchr/testify/mock"
)

// UserProxy is an autogenerated mock type for the UserProxy type
type UserProxy struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: ctx, userId
func (_m *UserProxy) GetUser(ctx context.Context, userId int64) (*identitypb.GetUserProfileResponse, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *identitypb.GetUserProfileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*identitypb.GetUserProfileResponse, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *identitypb.GetUserProfileResponse); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identitypb.GetUserProfileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserProxy creates a new instance of UserProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserProxy {
	mock := &UserProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
