// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/payment-mservice/server/repository/model"
)

// PaymentMethodDAO is an autogenerated mock type for the PaymentMethodDAO type
type PaymentMethodDAO struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, method
func (_m *PaymentMethodDAO) Create(ctx context.Context, method *model.UserPaymentMethod) error {
	ret := _m.Called(ctx, method)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserPaymentMethod) error); ok {
		r0 = rf(ctx, method)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *PaymentMethodDAO) GetActiveByUserID(ctx context.Context, userID int64) (*model.UserPaymentMethod, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByUserID")
	}

	var r0 *model.UserPaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.UserPaymentMethod, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.UserPaymentMethod); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserPaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PaymentMethodDAO) GetByID(ctx context.Context, id int64) (*model.UserPaymentMethod, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.UserPaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.UserPaymentMethod, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.UserPaymentMethod); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserPaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *PaymentMethodDAO) ListByUserID(ctx context.Context, userID int64) ([]*model.UserPaymentMethod, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*model.UserPaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*model.UserPaymentMethod, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*model.UserPaymentMethod); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserPaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertByProviderPaymentMethodID provides a mock function with given fields: ctx, method
func (_m *PaymentMethodDAO) UpsertByProviderPaymentMethodID(ctx context.Context, method *model.UserPaymentMethod) error {
	ret := _m.Called(ctx, method)

	if len(ret) == 0 {
		panic("no return value specified for UpsertByProviderPaymentMethodID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserPaymentMethod) error); ok {
		r0 = rf(ctx, method)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentMethodDAO creates a new instance of PaymentMethodDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodDAO {
	mock := &PaymentMethodDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
