// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/payment-mservice/server/repository/model"
)

// PaymentAccountDAO is an autogenerated mock type for the PaymentAccountDAO type
type PaymentAccountDAO struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, account
func (_m *PaymentAccountDAO) Create(ctx context.Context, account *model.UserPaymentAccount) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserPaymentAccount) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByUserIDAndProvider provides a mock function with given fields: ctx, userID, provider
func (_m *PaymentAccountDAO) GetByUserIDAndProvider(ctx context.Context, userID int64, provider string) (*model.UserPaymentAccount, error) {
	ret := _m.Called(ctx, userID, provider)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDAndProvider")
	}

	var r0 *model.UserPaymentAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*model.UserPaymentAccount, error)); ok {
		return rf(ctx, userID, provider)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *model.UserPaymentAccount); ok {
		r0 = rf(ctx, userID, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserPaymentAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentAccountDAO creates a new instance of PaymentAccountDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentAccountDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentAccountDAO {
	mock := &PaymentAccountDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
