// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/payment-mservice/server/repository/model"
)

// TransactionDAO is an autogenerated mock type for the TransactionDAO type
type TransactionDAO struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx
func (_m *TransactionDAO) Create(ctx context.Context, tx *model.Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByBizID provides a mock function with given fields: ctx, bizID
func (_m *TransactionDAO) GetByBizID(ctx context.Context, bizID string) (*model.Transaction, error) {
	ret := _m.Called(ctx, bizID)

	if len(ret) == 0 {
		panic("no return value specified for GetByBizID")
	}

	var r0 *model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Transaction, error)); ok {
		return rf(ctx, bizID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Transaction); ok {
		r0 = rf(ctx, bizID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bizID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPaymentID provides a mock function with given fields: ctx, paymentID
func (_m *TransactionDAO) GetByPaymentID(ctx context.Context, paymentID string) (*model.Transaction, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPaymentID")
	}

	var r0 *model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Transaction, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Transaction); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusByPaymentID provides a mock function with given fields: ctx, paymentID, status, remark
func (_m *TransactionDAO) UpdateStatusByPaymentID(ctx context.Context, paymentID string, status string, remark string) error {
	ret := _m.Called(ctx, paymentID, status, remark)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusByPaymentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, paymentID, status, remark)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionDAO creates a new instance of TransactionDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionDAO {
	mock := &TransactionDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
